name: CI & CD
on:
    push:
        branches:
            - master
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Data repository
              uses: actions/checkout@v3
              with:
                  lfs: true
            - name: Checkout Program repository
              uses: actions/checkout@v3
              with:
                  repository: ${{ secrets.GIT_URI }}
                  path: super/
            - name: Merge Data & Program
              run: |
                  shopt -s extglob
                  mv !(super) super/source/
                  shopt -s dotglob
                  rm -rf .git/ .github/
                  mv super/* .
            - uses: pnpm/action-setup@v2
              with:
                version: 8
            - uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: pnpm
            - name: Install & Build
              run: pnpm i  &&  pnpm build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./public
                  cname: fcc-cd.dev
                  external_repository: ${{ secrets.GIT_URI }}
                  publish_branch: master
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  force_orphan: true